version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    reviewers:
      - "d4rkfella"
    assignees:
      - "d4rkfella"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      gomod-updates:
        patterns:
          - "*"
